[package]
name = "activelook-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary-layout = "4.0.1"
binrw = "0.13.3"
deku = "0.16.0"
